### ISSUE TITLE
Consolidate shared env vars in template config

### ISSUE THREAD

**Issue by farski** [PRX/Infrastructure#20]
There are a number of env vars, in a given environment type, are shared by many apps (eg the host name for the ID service), and it would be a bit cleaner to have a single template config definition that just gets reused.

**Comment by farski** [comment]
Been working on this to slim up the template config file. @cavis there are some mostly-shared HOST values, but some apps seem to just expect a host, and some expect a URL with a scheme (eg play.prx.org vs http://play.prx.org) How would you feel about standardizing around host-only?

**Comment by cavis** [comment]
Naming standards are fine by me.  There is a bit of work to make sure all the apps consistently recognize `.docker` / `.dev` hosts, and don't try to use https there.  Otherwise... i _think_ all our tech/org services use SSL.

The only slight gotcha would be a prod service with both tech and org DNS, but only the org cert.  But since we're only using those to swap/promote a .tech to a .org, I don't think we'll run into any issues there.

**Comment by farski** [comment]
This is mostly not a thing anymore because app configs are being move to app-specific secrets
